# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
            ],
            options={
                'verbose_name_plural': 'points of interest',
            },
        ),
    ]
