# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='hood',
        ),
        migrations.AddField(
            model_name='bio',
            name='user_hood',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hood.Hood'),
            preserve_default=False,
        ),
    ]
