# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='title',
        ),
    ]
