# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20180624_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='geom',
            field=djgeojson.fields.PolygonField(blank=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(blank=True, upload_to='p'),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
