# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='location',
        ),
    ]
