# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20180627_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
