# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_status_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hood.Hood'),
            preserve_default=False,
        ),
    ]
