# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 12:50
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_auto_20180629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
